name: Latest Release

on:
  push:
    branches: [ "main" ]

# 🌟 关键：显式声明这个工作流拥有仓库内容的写入权限 🌟
permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - name: Package Binary
        shell: powershell
        run: |
          $APP_NAME = "slint-windows-mica-template"
          Compress-Archive -Path "target/release/$APP_NAME.exe" -DestinationPath "$APP_NAME-windows.zip"

      - name: Update Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Latest Build (Nightly)"
          tag_name: "nightly"
          prerelease: true
          files: slint-windows-mica-template-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}